packages:
  - "apps/*"
  - "packages/*"
overrides:
  lodash: ^4.18.1
  postcss: ^8.5.25
  sharp: ^0.35.3
  '@nestjs/swagger>js-yaml': ^4.3.1
  hono: ^4.12.34
  nanoid: ^3.3.17
  deepmerge-ts: ^8.0.0
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true
  usb: true
